spring.application.name=sbsqlite0801

server.port=8888

spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.url=jdbc:sqlite:employees.db
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# update , validate  , create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.column_ordering_strategy=legacy

#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql